### ISSUE TITLE
Login mit Email und Bestellnummer funktioniert nicht

### ISSUE THREAD

**Issue by herstellerangebote** [zencartpro/157-modul-cowoa#1]
Achtung! E-Mail Adresse oder Passwort wurden nicht gefunden - means: Caution! Email or password wer not found.

In my case cowoa only works with php-7.4.29. Php-8.0.x results in a error 500

**Comment by webchills** [comment]
@ Login mit Email und Bestellnummer
Nur möglich wenn Konfiguration > Bestellen ohne Kundenkonto > Bestellstatus aktivieren auf true steht.
Dann enthält die Bestellbestätigung den speziellen Link zur Bestellstatusabfrage:
index.php?main_page=order_status
Auf dieser Seite werden dann Bestellnummer und Email erwartet und auch problemlos akzeptiert

@ Error 500 unter PHP 8
Welche Aktion wird genau ausgeführt wenn es zu einem solchen Error kommt?
