### ISSUE TITLE
Bei Geschenkgutscheinen COWOA-Anmeldung rausgenommen

### ISSUE THREAD

**Issue by Anton2024tf** [zencartpro/157-modul-cowoa#2]
Hallo, 
damit Geschenkgutscheine nicht ohne Kund*innenkonto bestellt werden können habe ich in der Datei 

includes/templates/responsive_classic/templates/tpl_login_default.php

die beiden Zeilen 
`<?php if ($_SESSION['cart']->count_contents() > 0) { ?>`

ersetzt durch 
`<?php  if ($_SESSION['cart']->count_contents() > 0 && (strcmp($_SESSION['cart']->get_content_type(),"physical")==0)) { ?>`

Dachte, ich schreibe es hier mal, für den Fall, dass Ihr das generell in den Code mit aufnehmen wollt. Oder vielleicht gibt es ja einen guten Grund, das sowas bisher nicht im Code ist? Oder ich übersehe eine Einstellung, mit der das einfacher geht?

**Comment by webchills** [comment]
Prinzipiell ist es super, COWOA bei Geschenkgutscheinen zu deaktivieren. Die Abfrage nach physical only scheint mir aber zu radikal, dadurch können auch keine Downloadartikel mit COWOA bestellt werden. Für Downloadshops ist das problematisch.
Um nur Geschenkgutscheine nicht zu erlauben, wäre sowas hier vielleicht besser geeignet:
`<?php if (COWOA_STATUS == 'true' && ($_SESSION['cart']->in_cart_check('master_categories_id','21') == 0)) { ?> `
Die ID der Kategorie, in der die Geschenkgutscheine sind, müsste dann halt manuell von 21 angepasst werden.

**Comment by Anton2024tf** [comment]
Daran hatte ich nicht gedacht, da ich keine Downloads im shop habe. Aber das könnte sich ja ändern und ich änder das demnächst dann mal entsprechend.

**Comment by webchills** [comment]
added to 3.9.3
